######################################################################################################
# 注意事项
# 1. 所有没有批次信息的样本的KitDate统一为1991-01-01
######################################################################################################

# 2022-09-01 到 2022-09-30增加的样本


filter: &filter {
      Ignore: 0, TimePoint: {"$nin": [after-surgery]},
      GroupLevel2: {"$nin": [MAC or SRCC]},
      GroupLevel3: {"$nin": ["Mixed-SRC", "PIN", "Liver cirrhosis", "lung nodules", "breast nodule",
                             "Benign prostatic hyperplasia", "Renal Hamartoma", "Complex Renal Cyst", "breast nodules"]
      },
    }

dataset:
  0831-0930:
    filter: *filter
    select:
      0901-0920:
       - {KitDate: { "$gt": 2022-09-01T00:00:00+08:00, "$lte": 2022-09-30T23:59:59+08:00 }}