######################################################################################################
# 注意事项
# 1. 所有没有批次信息的样本的KitDate统一为1991-01-01
######################################################################################################

# 5715数据集


description:
  K799: 复旦大学附属肿瘤医院/王征
  KA7V: 中国医学科学院肿瘤医院/高树庚
  KY249: 江苏省肿瘤医院/尹荣
  Rep95: 肺癌旧实验流程，信灵采血管，5人，每人3个重复
  KB48: 中国医科大学附属第一医院/许顺
  KAL1: 长海医院/任善成
  KY256: 中山大学附属肿瘤医院/王峰
  KAG9_202106: 金陵队列老实验流程
  KB4Q: 中国医学科学院肿瘤医院/苏建忠
  KB53: 长癌医院/王林辉
  KA5Q: 复旦大学附属肿瘤医院/彭俊杰
  KAG9_202201: 金陵队列新湿实验流程
  Y152: 旧实验流程，大部分人工，大部分EDTA采血管
  Y00D: 旧实验流程，大部分自动化，大部分Streck采血管
  Baseline-EDTA-Streck: EDTA，Streck采血管，用于采血管矫正基线样本
  Rep69: 旧实验流程稳定性测试，8人*3rep
  TubeTest_NJ-BJ-GZ: 采血管优化实验：10个健康人，Streck，Bunny新旧，Bunny成分18,19,20，不同运输时间，人工磁珠提取，KAPA自动化建库
  Old_New_SOP_compare: 金陵队列旧实验流程，用于新老湿实验流程对比实验
  Old_New_SOP_repeat: 金陵队列旧实验流程，用于旧湿实验流程重复性评价
  KAG9_202205: KAG9新实验流程（人工提取）
  R083: 江苏省肿瘤医院/尹荣
  KAE3: 南京鼓楼医院肺癌/王立峰
  PlosOne: "Ma X, Zhu L, Wu X, et al. PloS one, 2017, 12(1): e0169231."
  KAT6: 广州医科大学附属第一医院/古迪
  KY400:
  KY387: 科研项目，非早筛实验流程Xten测序，PCR WGS数据
  PRJNA578569: "Bujak A Z, Weng C F, Silva M J, et al. Annals of Oncology, 2019, 30: v30."
  PRJNA633741: "Wei T, Zhang J, Li J, et al.Molecular oncology, 2020, 14(9): 1966-1977."
  KAG9_202202: 金陵队列新实验流程
  INR10: 尤明day0天采血，重复10次，老实验流程
  INR20: 尤明day15天，30天采血，各重复10次，老实验流程
  20210730_Tube_and_Save: 采血管优化实验：EDTA/Streck/Higia/Bunny， 常温/低温/高温运输
  TimeComStab: 采血管优化实验： 5个健康人，EDTA，Streck，Bunny不同成分，不同空管放置时间，每个条件两个重复，人工磁珠提取，Qiagen自动化建库
  YZ15_optimize: 磁珠提取STAR自动化测试实验（建库旧流程）：凯杰；磁珠人工；磁珠自动化批内批间
  PRJNA795275: "Esfahani M S, Hamilton E G, Mehrmohamadi M, et al. Nature Biotechnology, 2022: 1-13."
  S94U: 中国医学科学院肿瘤医院/苏建忠
  Protease312: 血浆提取流程更换蛋白酶K 翎圣vs瀚海 优化实验，1肺癌样本*2
  Protease421: 血浆提取流程更换蛋白酶K 翎圣vs瀚海 优化实验2，1肺癌样本*2
  R007: 晚期肺癌，用于肺癌早筛文章补充验证
  PRJNA627029: https://www.ncbi.nlm.nih.gov/sra/?term=PRJNA627029
  PRJNA489753: "Agarwal R, Chan Y C, Tam C S, et al. Nature Medicine, 2019, 25(1): 119-129."
  PRJNA393138: "Cutts A, Venn O, Dilthey A, et al.NPJ genomic medicine, 2017, 2(1): 1-8."
  PRJNA554329: "Ramesh N, Sei E, Tsai P C, et al. Genome biology, 2020, 21(1): 1-22."
  Cleavage312: cfDNA磁珠法提取3次裂解vs2次裂解优化实验，3人*2rep
  Cleavage419: cfDNA磁珠法提取裂解次数1次vs2次vs3次优化实验，5人*9rep
  Protease313: 血浆提取流程更换蛋白酶K 翎圣vs瀚海 优化实验，3健康样本*2


features:
  Cnv_5X: /dssg02/InternalResearch02/Mercury/Monthly_Presentation_Analysis/2022_06_PanCancer/Feature5222/cnv.csv
  combine2: /dssg02/InternalResearch02/Mercury/Monthly_Presentation_Analysis/2022_06_PanCancer/Feature5222/combine2.csv

dataset:
  train:
    filter: {
      KitDate: {"$lte": 2022-07-13T01:00:00+08:00}, Ignore: 0, TimePoint: {"$nin": [after-surgery]},
      GroupLevel2: {"$nin": [MAC or SRCC]},
      GroupLevel3: {"$nin": ["Mixed-SRC", "PIN", "Liver cirrhosis", "lung nodules", "breast nodule",
                             "Benign prostatic hyperplasia", "Renal Hamartoma", "Complex Renal Cyst", "breast nodules"]
      },
    }
    select:
        K799:
          - {ProjectID: K799, GroupLevel1: Disease, GroupLevel2: Disease, GroupLevel3: HBV positive}
          - {ProjectID: K799, GroupLevel1: Cancer, GroupLevel2: Liver, GroupLevel3: PLC, GroupLevel4: HCC, ratio: [0, 0.6]}

        KA7V:
          - {ProjectID: KA7V, GroupLevel1: Cancer, GroupLevel2: Lung, GroupLevel3: NSCLC}

        KY249:
          - {ProjectID: KY249, GroupLevel1: Cancer, GroupLevel2: Lung, GroupLevel3: NSCLC}

        Rep95:
          - {ProjectID: Rep95, GroupLevel1: Cancer, GroupLevel2: Lung, GroupLevel3: NSCLC}
          - {ProjectID: Rep95, GroupLevel1: Healthy, GroupLevel2: Healthy}

        Old_New_SOP_compare:
          - {ProjectID: Old_New_SOP_compare, GroupLevel1: Cancer, GroupLevel2: Lung, GroupLevel3: NSCLC}
          - {ProjectID: Old_New_SOP_compare, GroupLevel1: Healthy, GroupLevel2: Healthy}

        Old_New_SOP_repeat:
          - {ProjectID: Old_New_SOP_repeat, GroupLevel1: Cancer, GroupLevel2: Lung, GroupLevel3: NSCLC}
          - {ProjectID: Old_New_SOP_repeat, GroupLevel1: Healthy, GroupLevel2: Healthy}

        KB6A:
          - {ProjectID: KB6A, GroupLevel1: Cancer, GroupLevel2: Lung, GroupLevel3: NSCLC}

        KB1C:
          - {ProjectID: KB1C, GroupLevel1: Cancer, GroupLevel2: Lung, GroupLevel3: NSCLC}

        KB48:
          - {ProjectID: KB48, GroupLevel1: Cancer, GroupLevel2: Lung, GroupLevel3: NSCLC}

        KA5Q:
          - {ProjectID: KA5Q, GroupLevel1: Cancer, GroupLevel2: Colorectal, GroupLevel3: CRC}
          - {ProjectID: KA5Q, GroupLevel1: Disease, GroupLevel2: Disease, GroupLevel3: CRA, ratio: [0, 0.5]}

        KY087:
          - {ProjectID: KY087, GroupLevel1: Cancer, GroupLevel2: Colorectal, GroupLevel3: CRC}

        KAL1:
          - {ProjectID: KAL1, GroupLevel1: Cancer, GroupLevel2: Prostate, GroupLevel3: PCA}

        KAT6:
          - {ProjectID: KAT6, GroupLevel1: Cancer, GroupLevel2: Prostate, GroupLevel3: PCA, KitDate: {"$gte": 2022-06-01T01:00:00+08:00}}

        KY256:
          - {ProjectID: KY256, GroupLevel1: Cancer, GroupLevel2: Gastric, ratio: [0, 0.5]}

        KB4Q:
          - {ProjectID: KB4Q, GroupLevel1: Cancer, GroupLevel2: Breast}

        KB53:
          - {ProjectID: KB53, GroupLevel1: Cancer, GroupLevel2: Kidney}


        Y00D:
          - {ProjectID: Y00D, GroupLevel1: Disease, GroupLevel2: Disease, GroupLevel3: HBV positive}
          - {ProjectID: Y00D, GroupLevel1: Disease, GroupLevel2: Disease, GroupLevel3: healthy (drug or disease)}
          - {ProjectID: Y00D, GroupLevel1: Healthy, GroupLevel2: Healthy}

        Y152:
          - {ProjectID: Y152, GroupLevel1: Disease, GroupLevel2: Disease, GroupLevel3: healthy (drug or disease)}
          - {ProjectID: Y152, GroupLevel1: Healthy, GroupLevel2: Healthy}

        Rep69:
          - {ProjectID: Rep69, GroupLevel1: Disease, GroupLevel2: Disease, GroupLevel3: healthy (drug or disease)}
          - {ProjectID: Rep69, GroupLevel1: Healthy, GroupLevel2: Healthy}

        Baseline-EDTA-Streck:
          - {ProjectID: Baseline-EDTA-Streck, GroupLevel1: Healthy, GroupLevel2: Healthy}

        TubeTest_NJ-BJ-GZ:
          - {ProjectID: TubeTest_NJ-BJ-GZ, GroupLevel1: Healthy, GroupLevel2: Healthy}

        KAG9_202205:
          - {ProjectID: KAG9, GroupLevel1: Healthy, GroupLevel2: Healthy, KitDate: {"$gte": 2022-04-01T01:00:00+08:00, "$lte": 2022-05-30T01:00:00+08:00}}

        KAG9_202206:
          - {ProjectID: KAG9, GroupLevel1: Healthy, GroupLevel2: Healthy, KitDate: {"$gte": 2022-06-01T01:00:00+08:00, "$lte": 2022-06-11T23:59:59+08:00}}

        KAS7:
          - {ProjectID: KAS7, GroupLevel1: Healthy, GroupLevel2: Healthy, KitDate: {"$lte": 2022-06-11T01:00:00+08:00}}

  Valid:
    filter: {
      KitDate: { "$lte": 2022-07-13T01:00:00+08:00 }, Ignore: 0, TimePoint: { "$nin": [ after-surgery ] },
      GroupLevel2: { "$nin": [ MAC or SRCC ] },
      GroupLevel3: { "$nin": [ "Mixed-SRC", "PIN", "Liver cirrhosis", "lung nodules", "breast nodule",
                               "Benign prostatic hyperplasia", "Renal Hamartoma", "Complex Renal Cyst", "breast nodules" ]
      },
    }
    select:
      K799:
        - {ProjectID: K799, GroupLevel1: Cancer, GroupLevel2: Liver, GroupLevel3: PLC, GroupLevel4: HCC, ratio: [0.6, 1]}
        - {ProjectID: K799, GroupLevel1: Cancer, GroupLevel2: Liver, GroupLevel3: PLC, GroupLevel4: {"$ne": HCC}}

      R083:
        - {ProjectID: R083, GroupLevel1: Cancer, GroupLevel2: Lung, GroupLevel3: NSCLC}

      KB11:
        - {ProjectID: KB11, GroupLevel1: Cancer, GroupLevel2: Lung, GroupLevel3: NSCLC}

      KAG9_202206:
        - { ProjectID: KAG9,  KitDate: {"$gte": 2022-06-11T23:59:59+08:00, "$lte": 2022-06-16T23:59:59+08:00 } }

      KAE3:
        - {ProjectID: KAE3, GroupLevel1: Cancer, GroupLevel2: Lung, GroupLevel3: NSCLC}
        - {ProjectID: KAE3, GroupLevel1: Healthy, GroupLevel2: Healthy}

      PlosOne:
        - {ProjectID: PlosOne, GroupLevel1: Cancer, GroupLevel2: Lung, GroupLevel3: NSCLC}
        - {ProjectID: PlosOne, GroupLevel1: Cancer, GroupLevel2: Gastric, TimePoint: before-surgery}

      KY256:
        - {ProjectID: KY256, GroupLevel1: Cancer, GroupLevel2: Gastric, TimePoint: before-surgery, ratio: [0.5, 1]}

      Rep69:
        - {ProjectID: Rep69, GroupLevel1: Cancer, GroupLevel2: Colorectal, GroupLevel3: CRC}

      KY400:
        - {ProjectID: KM97(KY400), GroupLevel1: Cancer, GroupLevel2: Colorectal, GroupLevel3: CRC}
        - {ProjectID: KM97(KY400), GroupLevel1: Disease, GroupLevel2: Disease, GroupLevel3: CRA}

      KB4Q_S94U:
        - {ProjectID: KB4Q (S94U), GroupLevel1: Cancer, GroupLevel2: Breast}

      KAT6:
        - {ProjectID: KAT6, GroupLevel1: Cancer, GroupLevel2: Prostate, GroupLevel3: PCA, KitDate: {"$lte": 2022-05-31T01:00:00+08:00}}

      KAG9_202106:
        - {ProjectID: KAG9,  KitDate: {"$lte": 2021-06-30T01:00:00+08:00}}

      KA5Q:
        - {ProjectID: KA5Q, GroupLevel1: Disease, GroupLevel2: Disease, GroupLevel3: CRA, ratio: [0.5, 1]}

      KY387:
        - {ProjectID: KY387, GroupLevel1: Disease, GroupLevel2: Disease, GroupLevel3: CRA}

      PRJNA578569:
        - {ProjectID: PRJNA578569, GroupLevel1: Cancer, GroupLevel2: Breast}

      PRJNA633741:
        - {ProjectID: PRJNA633741, GroupLevel1: Cancer, GroupLevel2: Pancreatic}

      KAG9_202202:
        - {ProjectID: KAG9,  KitDate: {"$gte": 2021-07-01T01:00:00+08:00, "$lte": 2022-02-28T01:00:00+08:00}}

      INR30:
        - {ProjectID: INR30, GroupLevel1: Healthy, GroupLevel2: Healthy}


      20210730_Tube_and_Save:
        - {ProjectID: 20210730_Tube_and_Save, GroupLevel1: Healthy, GroupLevel2: Healthy}

      TimeComStab:
        - {ProjectID: TimeComStab, GroupLevel1: Healthy, GroupLevel2: Healthy}

      YZ15_optimize:
        - {ProjectID: YZ15_optimize, GroupLevel1: Healthy, GroupLevel2: Healthy}

      PRJNA795275:
        - {ProjectID: PRJNA795275, GroupLevel1: Healthy, GroupLevel2: Healthy}

  Test:
    filter: {
      KitDate: { "$lte": 2022-07-13T01:00:00+08:00 }, Ignore: 0, TimePoint: { "$nin": [ after-surgery ] },
      GroupLevel2: { "$nin": [ MAC or SRCC ] },
      GroupLevel3: { "$nin": [ "Mixed-SRC", "PIN", "Liver cirrhosis", "lung nodules", "breast nodule",
                               "Benign prostatic hyperplasia", "Renal Hamartoma", "Complex Renal Cyst", "breast nodules" ]
      },
    }
    select:
      S94U:
        - {ProjectID: S94U, GroupLevel1: Cancer, GroupLevel2: Breast}

      KBM3:
        - {ProjectID: KBM3, GroupLevel1: Cancer, GroupLevel2: Lung}

      KB8Y:
        - {ProjectID: KB8Y}

      Protease312:
        - {ProjectID: Protease312}

      Protease421:
        - {ProjectID: Protease421}

      KY387:
        - {ProjectID: KY387, GroupLevel1: Cancer, GroupLevel2: Colorectal, GroupLevel3: CRC}

      KB3V:
        - {ProjectID: KB3V}

      R007:
        - {ProjectID: R007, GroupLevel1: Cancer, GroupLevel2: Lung}

      PRJNA627029:
        - {ProjectID: PRJNA627029, GroupLevel1: Cancer, GroupLevel2: Breast}

      PRJNA489753:
        - {ProjectID: PRJNA489753, GroupLevel1: Cancer, GroupLevel2: lymphoma, GroupLevel3: Mantle cell lymphoma}

      PRJNA393138:
        - {ProjectID: PRJNA393138, GroupLevel1: Cancer, GroupLevel2: Melanoma}

      PRJNA554329:
        - {ProjectID: PRJNA554329, GroupLevel1: Cancer, GroupLevel2: Prostate}

      Cleavage313:
        - {ProjectID: Cleavage313, GroupLevel1: Healthy, GroupLevel2: Healthy}

      Cleavage419:
        - {ProjectID: Cleavage419, GroupLevel1: Healthy, GroupLevel2: Healthy}

      KAS7:
        - {ProjectID: KAS7, GroupLevel1: Healthy, GroupLevel2: Healthy, KitDate: {"$gte": 2022-06-11T01:00:00+08:00, "$lte": 2022-07-13T01:00:00+08:00}}

      KBL1:
        - {ProjectID: KBL1, GroupLevel1: Healthy, GroupLevel2: Healthy}

      R007_Stable:
        - {ProjectID: R007_Stable}

      R007_save:
        - {ProjectID: R007_save, GroupLevel1: Healthy, GroupLevel2: Healthy}

      R007_tube_compare:
        - {ProjectID: R007_tube_compare, GroupLevel1: Healthy, GroupLevel2: Healthy}

      KAG9_202206:
        - { ProjectID: KAG9,  KitDate: { "$gte": 2022-06-16T23:59:59+08:00, "$lte": 2022-07-13T01:00:00+08:00 }}


